# Generated by Django 2.1 on 2022-06-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_record_text_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sentenceNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
